#define QS_CMD_HALT 0x02
#define QS_CMD_STEPDIR  0x84

#define QS_CMD_ENABLE_DRIVER  0xE3
#define QS_CMD_DISABLE_DRIVER  0xE4
#define QS_CMD_STOP  0x03
#define QS_CMD_REBOOT  0x04

#define QS_CMD_MOVEABS_VELOCITYBASED  0x86
#define QS_CMD_MOVEREL_VELOCITYBASED  0x87

#define QS_CMD_MOVEABS_TIMEBASED  0xB0
#define QS_CMD_MOVEREL_TIMEBASED  0xB1
#define QS_CMD_MODE_VELOCITYCONTROL 0xD9 
#define QS_CMD_MODE_VELOCITYIMMEDIATE 0xF
#define QS_CMD_ENABLE_MOTOR_DRIVER 0xE3
#define QS_CMD_DISABLE_MOTOR_DRIVER 0xE4
//#define QS_CMD_HARD_STOP 0xE5
#define QS_CMD_HARD_STOP 0x2
#define QS_CMD_STOP_MOTION 0x3
#define QS_CMD_RESTART 0x4