
#ifndef _spi_proto_h
#define _spi_proto_h

#define FOREACH_ELEM(ERRCODE) \
        ERRCODE(ACK_OK)   \
        ERRCODE(ACK_NOK)  \
        ERRCODE(ACK_UNKNOWN)   \
        ERRCODE(ACK_ERR_INVALID_STARTBYTE)  \
        ERRCODE(ACK_CONN_OK)  \
        ERRCODE(ACK_RESET)  \
        ERRCODE(ACK_ERR_INVALID_COMMAND) \
        ERRCODE(ACK_ERR_TIMEOUT_WAITING_SERVO_RESPONSE) \
        ERRCODE(ACK_ERR_BUFFER_OVERFLOW) \
        ERRCODE(ERR_QS_COMM_TIMEOUT) \

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

enum SPI_QS_ERRORCODES {
    FOREACH_ELEM(GENERATE_ENUM)
    LASTELEM = ERR_QS_COMM_TIMEOUT
};

char* getSpiCommMsgText(uint8_t errorCode);

#endif